### ISSUE TITLE
New Emotion Collection Missing some Metadata on Neurolearn

### ISSUE THREAD

**Issue by ljchang** [neurolearn/neurolearn-web#16] opened 2016-11-07 06:24 UTC
I added a new IAPS rating dataset today with 822 [images](http://neurovault.org/collections/1964/).  For some reason only 65 images labeled 'train' are showing up with metadata during model training stage.  Maybe not all of the data transferred completely?

Also, I'm updating collection 503 with missing images and metadata.  @burnash I'll let you know when it's ready to reload completely on neurolearn.

**Comment by ljchang** [comment] 2016-11-09 12:40
Here is some more info about the bug.  If you select all of the data it is only retaining 100 rows of the image metadata in the handsontable when selecting the training labels even though all of the data appears to be showing up when selecting it.

**Comment by burnash** [comment] 2016-11-09 12:45
The it's a bug indeed. The problem is that the code is skipping pagination in this request. This has top priority in my bug list.

**Comment by burnash** [comment] 2016-11-17 04:36
I reworked image data fetching in the app and fixed the pagination issue. However, for some collections, the results may still be inconsistent due to a bug in the NeuroVault API. I've submitted a fix and are waiting for it to be deployed. (Also related to  #17)

**Comment by burnash** [comment] 2016-12-10 10:18
The pagination issue is now fixed both in browser and on the server (57ffee54973520ee76dfbbe37ef2fd6b019f3053). I used all 822 images of 
the "Affective Ratings to Emotional Images" collection for a new model and the training went fine: http://neuro-learn.org/models/66 

The next step, I think, is to find out how big the training data can be.

**Closed by burnash** 2016-12-10 10:18 UTC
Labels: bug
